import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuroraBackgroundDemo } from "@/components/AuroraBackgroundDemo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <AuroraBackgroundDemo>
          <main className="h-[80vh] w-full">{children}</main>
        </AuroraBackgroundDemo>
      </body>
      
    </html>
  );
}
